export GOPATH=$HOME/go
export PATH=${PATH}:$HOME/bin:/usr/local/sbin:$HOME/.rvm/bin:/usr/bin:/usr/local/bin:/usr/local/opt/python/libexec/bin:/usr/local/opt/ruby/bin:
export BLOCKSIZE=1k
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache
export WORKON_HOME=$HOME/pythonenvs
export EDITOR=vi
export VISUAL=vi
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=0
export PATH="/opt/homebrew/opt/m4/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/postgresql@12/lib $LDFLAGS"
export LDFLAGS="-L/usr/local/opt/libq/lib $LDFLAGS"
export CPPFLAGS="-I/usr/local/opt/postgresql@12/include $CPPFLAGS"
export PATH="/usr/local/opt/postgresql@12/bin:$PATH"
export PATH="/usr/local/opt/node@16/bin:$PATH"
export PATH="/usr/local/opt/postgresql@13/bin:$PATH"
